### ISSUE TITLE
Establish some initial standards for the project.

### ISSUE THREAD

**Issue by borgified** [Alan-R/rust-nanoprobe#13]
1. Standards for code creation (formatting, etc)
2. Standards for where to put documents (wiki??) - this may depend on the intended audience - developer versus end user, for example.
3. Standards for creating unit tests
4. Standards for tracking progress (should it be Trello, GitHub, other?)
5. Standards for communication

It is understood that this will change over time. That’s expected!

**Comment by Alan-R** [comment]
This duplicates an existing issue.
